version: "2.2"
services:
  zookeeper:
    image: pi-zookeeper:latest
    build: 
      context: ./zookeeper
      network: host
    ports:
      - 2181:2181
  hadoop:
    image: pi-hadoop:latest
    build:
      context: ./hadoop
      network: host
    ports:
      - 50070:50070 # namenode
      - 50090:50090 # secondary namenode
    tty: true
  accumulo:
    image: pi-accumulo:latest
    build:
      context: ./accumulo
      network: host
    links:
      - zookeeper
      - hadoop
    depends_on:
      - zookeeper
    tty: true