version: "2.0"
services:
  zookeeper:
    build: ./zookeeper
    container_name: zookeeper-container
    restart: always
  hadoop:
    build: ./hadoop
    container_name: hadoop-container
    restart: always